"""empty message

Revision ID: 0ad4f9ca594b
Revises: d98de01d38c5
Create Date: 2022-07-31 00:12:00.181034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad4f9ca594b'
down_revision = 'd98de01d38c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('summarized_content', sa.String(), nullable=True))
    op.add_column('text', sa.Column('synonymized_content', sa.String(), nullable=True))
    op.add_column('text', sa.Column('lemmatized_summarized_content', sa.String(), nullable=True))
    op.add_column('text', sa.Column('lemmatized_synonymized_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'lemmatized_synonymized_content')
    op.drop_column('text', 'lemmatized_summarized_content')
    op.drop_column('text', 'synonymized_content')
    op.drop_column('text', 'summarized_content')
    # ### end Alembic commands ###
