"""empty message

Revision ID: 1710bc2632c3
Revises: 7ebe42d16efe
Create Date: 2022-07-26 19:30:47.473112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1710bc2632c3'
down_revision = '7ebe42d16efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('title', sa.String(), nullable=True))
    op.create_index(op.f('ix_text_title'), 'text', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_title'), table_name='text')
    op.drop_column('text', 'title')
    # ### end Alembic commands ###
