"""empty message

Revision ID: 692df012a26b
Revises: 
Create Date: 2022-07-21 21:56:39.339235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692df012a26b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=64), nullable=True),
    sa.Column('definition', sa.String(length=512), nullable=False),
    sa.Column('translation', sa.String(length=128), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_lemma'), 'word', ['lemma'], unique=True)
    op.create_table('user_word',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('number_of_times_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'word_id')
    )
    op.create_index(op.f('ix_user_word_number_of_times_seen'), 'user_word', ['number_of_times_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_word_number_of_times_seen'), table_name='user_word')
    op.drop_table('user_word')
    op.drop_index(op.f('ix_word_lemma'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
