"""empty message

Revision ID: 6b2335670110
Revises: 459762b658ab
Create Date: 2022-07-30 11:06:29.744382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2335670110'
down_revision = '459762b658ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_text', sa.Column('total_pages', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_text_total_pages'), 'user_text', ['total_pages'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_text_total_pages'), table_name='user_text')
    op.drop_column('user_text', 'total_pages')
    # ### end Alembic commands ###
