"""empty message

Revision ID: 710d2212217a
Revises: c2b7268dddf8
Create Date: 2022-07-26 19:22:15.433312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710d2212217a'
down_revision = 'c2b7268dddf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_text_title', table_name='text')
    op.create_index(op.f('ix_text_title'), 'text', ['title'], unique=False)
    op.drop_column('text', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_text_title'), table_name='text')
    op.create_index('ix_text_title', 'text', ['title'], unique=False)
    # ### end Alembic commands ###
