"""empty message

Revision ID: 7ebe42d16efe
Revises: 9e42432285e8
Create Date: 2022-07-26 19:30:36.501153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebe42d16efe'
down_revision = '9e42432285e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_text_title', table_name='text')
    op.drop_column('text', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_text_title', 'text', ['title'], unique=False)
    # ### end Alembic commands ###
