"""empty message

Revision ID: 9e42432285e8
Revises: 710d2212217a
Create Date: 2022-07-26 19:22:26.436182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e42432285e8'
down_revision = '710d2212217a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text', 'content')
    # ### end Alembic commands ###
