"""empty message

Revision ID: ab0f924e8dfc
Revises: 4ed27af5f1ca
Create Date: 2022-07-26 16:39:25.987122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0f924e8dfc'
down_revision = '4ed27af5f1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('unique_words', sa.Integer(), nullable=False),
    sa.Column('average_sentence_length', sa.Float(), nullable=False),
    sa.Column('average_word_length', sa.Float(), nullable=False),
    sa.Column('lemmatized_text', sa.String(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_title'), 'text', ['title'], unique=True)
    op.create_table('text_tag',
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.PrimaryKeyConstraint('text_id', 'tag_id')
    )
    op.create_table('user_text',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'text_id')
    )
    op.create_index(op.f('ix_user_text_current_page'), 'user_text', ['current_page'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_text_current_page'), table_name='user_text')
    op.drop_table('user_text')
    op.drop_table('text_tag')
    op.drop_index(op.f('ix_text_title'), table_name='text')
    op.drop_table('text')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
