"""empty message

Revision ID: c94130b39cbd
Revises: 0ad4f9ca594b
Create Date: 2022-08-01 11:55:11.111883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94130b39cbd'
down_revision = '0ad4f9ca594b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quizzes_done', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quizzes_done')
    # ### end Alembic commands ###
