"""empty message

Revision ID: cb4c0289fdaa
Revises: c94130b39cbd
Create Date: 2022-08-01 18:17:49.186383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c0289fdaa'
down_revision = 'c94130b39cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('goal_length_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'goal_length_minutes')
    # ### end Alembic commands ###
