"""empty message

Revision ID: d98de01d38c5
Revises: eccd3c531420
Create Date: 2022-07-30 13:16:22.354842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd98de01d38c5'
down_revision = 'eccd3c531420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elapsed_time_seconds', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_date'), 'log', ['date'], unique=False)
    op.create_index(op.f('ix_log_elapsed_time_seconds'), 'log', ['elapsed_time_seconds'], unique=False)
    op.drop_index('ix_logs_date', table_name='logs')
    op.drop_index('ix_logs_elapsed_time_seconds', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('elapsed_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    op.create_index('ix_logs_elapsed_time_seconds', 'logs', ['elapsed_time_seconds'], unique=False)
    op.create_index('ix_logs_date', 'logs', ['date'], unique=False)
    op.drop_index(op.f('ix_log_elapsed_time_seconds'), table_name='log')
    op.drop_index(op.f('ix_log_date'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
