"""empty message

Revision ID: eccd3c531420
Revises: 6b2335670110
Create Date: 2022-07-30 11:56:35.940311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccd3c531420'
down_revision = '6b2335670110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elapsed_time_seconds', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_date'), 'logs', ['date'], unique=False)
    op.create_index(op.f('ix_logs_elapsed_time_seconds'), 'logs', ['elapsed_time_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_elapsed_time_seconds'), table_name='logs')
    op.drop_index(op.f('ix_logs_date'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
